# -----------------------------------------------------------------------------
# main.tf — entry point for the main Terraform configuration
#
# This file does three things:
#   1. Declares which version of Terraform and which providers I need.
#   2. Configures the remote S3 backend so state is shared (backend details
#      come from backend.hcl, which is generated by the bootstrap step).
#   3. Configures the AWS provider with a default region and shared tags that
#      appear on every resource I create.
#
# I use an empty backend block here intentionally — the actual bucket name,
# region, and lock table are passed in at `terraform init` time via:
#   terraform init -backend-config=backend.hcl
# This avoids hardcoding account-specific values in version-controlled files.
# -----------------------------------------------------------------------------

terraform {
  required_version = ">= 1.9"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.4"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
  }

  # Empty backend — filled in at `terraform init -backend-config=backend.hcl`
  backend "s3" {}
}

provider "aws" {
  region = var.aws_region

  # Every AWS resource I create inherits these tags automatically.
  # This makes it easy to find all resources for this project in the console
  # and to set up cost allocation reports by environment.
  default_tags {
    tags = local.common_tags
  }
}

# I use this data source to look up the current AWS account ID at plan time.
# Several downstream resources (IAM policies, EB service role ARNs) need it.
data "aws_caller_identity" "current" {}
