# Use a Python image
FROM python:3.11-slim

# Set the working directory
WORKDIR /app

# Install system dependencies required for MariaDB, Pipenv, Netcat, and pkg-config
RUN apt-get update && apt-get install -y \
    mariadb-client \
    libmariadb-dev \
    pkg-config \
    gcc \
    build-essential \
    netcat-openbsd \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install pipenv 
RUN pip install pipenv

# Copy Pipfile
COPY Pipfile /app/

# Install dependencies using Pipenv (including dev packages)
RUN pipenv install --system --skip-lock --dev

# Copy the application code into the container
COPY . /app

# Expose the application's port
EXPOSE 8000

# Use the wait-for-db.sh script as entrypoint
ENTRYPOINT ["./wait-for-db.sh"]

# Run migrations before starting the application
CMD ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]