# -----------------------------------------------------------------------------
# Bootstrap — run this ONCE before anything else.
#
# I create an S3 bucket to store Terraform state remotely so every deploy
# reads and writes the same source of truth.
#
# After `terraform apply` here, a file called backend.hcl is written to the
# terraform/ directory above. That file tells the main configuration where to
# store state. You never commit it to git.
# -----------------------------------------------------------------------------

terraform {
  required_version = ">= 1.9"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.4"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
  }
}

provider "aws" {
  region = var.aws_region
}

variable "aws_region" {
  type    = string
  default = "us-east-1"
}

variable "project_name" {
  type    = string
  default = "humanlike-chatbot"
}

resource "random_id" "bucket_suffix" {
  byte_length = 4
}

resource "aws_s3_bucket" "terraform_state" {
  bucket = "${var.project_name}-tfstate-${random_id.bucket_suffix.hex}"

  lifecycle {
    prevent_destroy = true
  }

  tags = {
    Project   = var.project_name
    Purpose   = "terraform-state"
    ManagedBy = "terraform-bootstrap"
  }
}

resource "aws_s3_bucket_versioning" "terraform_state" {
  bucket = aws_s3_bucket.terraform_state.id
  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "terraform_state" {
  bucket = aws_s3_bucket.terraform_state.id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

resource "aws_s3_bucket_public_access_block" "terraform_state" {
  bucket                  = aws_s3_bucket.terraform_state.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "local_file" "backend_config" {
  filename        = "${path.module}/../backend.hcl"
  file_permission = "0600"

  content = <<-EOT
    # Generated by terraform/bootstrap — do not edit by hand.
    bucket  = "${aws_s3_bucket.terraform_state.bucket}"
    key     = "${var.project_name}/terraform.tfstate"
    region  = "${var.aws_region}"
    encrypt = true
  EOT
}

output "state_bucket_name" {
  value = aws_s3_bucket.terraform_state.bucket
}
