# Generated by Django 5.1.6 on 2025-03-06 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DefaultBotName', max_length=255, unique=True)),
                ('prompt', models.TextField()),
                ('model_type', models.CharField(default='OpenAI', max_length=255)),
                ('model_id', models.CharField(default='gpt-4', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=255, unique=True)),
                ('bot_name', models.CharField(default='DefaultBot', max_length=255)),
                ('participant_id', models.CharField(max_length=255)),
                ('initial_utterance', models.CharField(blank=True, max_length=255, null=True)),
                ('study_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_group', models.CharField(blank=True, max_length=255, null=True)),
                ('survey_id', models.CharField(blank=True, max_length=255, null=True)),
                ('survey_meta_data', models.TextField(blank=True, null=True)),
                ('started_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utterance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_id', models.CharField(max_length=255)),
                ('bot_name', models.CharField(blank=True, max_length=255, null=True)),
                ('participant_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utterances', to='chatbot.conversation')),
            ],
        ),
    ]
