# Generated by Django 5.1.7 on 2025-03-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_keystroke'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='initial_utterance',
            field=models.TextField(blank=True, null=True),
        ),
    ]
