# Generated by Django 5.2.3 on 2025-06-24 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_utterance_audio_file_utterance_is_voice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_type', models.CharField(choices=[('none', 'None'), ('default', 'Default'), ('user', 'User Provided')], default='none', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bot_avatars/')),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avatars', to='chatbot.bot')),
                ('bot_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_conversation', to='chatbot.conversation')),
            ],
        ),
    ]
