# Generated by Django 5.2.3 on 2025-07-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_bot_avatar_type_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_messages', models.BooleanField(default=True, help_text='If true, split into human-like chunks; if false, send as one blob')),
            ],
        ),
    ]
