# Generated by Django 5.2.3 on 2025-08-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_rename_image_path_avatar_chatbot_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='chunk_messages',
            field=models.BooleanField(default=True, help_text='If true, split responses into human-like chunks; if false, send as one blob'),
        ),
    ]
