# Generated by Django 5.2.3 on 2025-08-07 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_persona_bot_personas'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='selected_persona',
            field=models.ForeignKey(blank=True, help_text='The persona randomly selected for this conversation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='chatbot.persona'),
        ),
    ]
