# Generated by Django 5.2.5 on 2025-08-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_bot_follow_up_instruction_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='humanlike_delay',
            field=models.BooleanField(default=True, help_text='If true, apply human-like typing delays; if false, show messages instantly'),
        ),
        migrations.AddField(
            model_name='control',
            name='humanlike_delay',
            field=models.BooleanField(default=True, help_text='If true, apply human-like typing delays; if false, show messages instantly'),
        ),
    ]
