# Generated by Django 5.2.5 on 2025-08-09 20:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_bot_follow_up_instruction_prompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utterance',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
