# Generated by Django 5.2.5 on 2025-08-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0014_remove_control_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='first_chunk_thinking_ms',
            field=models.IntegerField(default=600, help_text='Additional milliseconds for the first chunk (thinking time)'),
        ),
        migrations.AddField(
            model_name='bot',
            name='last_chunk_pause_ms',
            field=models.IntegerField(default=100, help_text='Additional milliseconds for the last chunk'),
        ),
        migrations.AddField(
            model_name='bot',
            name='max_delay_ms',
            field=models.IntegerField(default=800, help_text='Maximum delay in milliseconds (when backend is slow)'),
        ),
        migrations.AddField(
            model_name='bot',
            name='min_delay_ms',
            field=models.IntegerField(default=200, help_text='Minimum delay in milliseconds (when backend is fast)'),
        ),
        migrations.AddField(
            model_name='bot',
            name='question_thinking_ms',
            field=models.IntegerField(default=300, help_text='Additional milliseconds for chunks containing questions'),
        ),
        migrations.AddField(
            model_name='bot',
            name='typing_speed_max_ms',
            field=models.IntegerField(default=200, help_text='Maximum milliseconds per character for typing speed (base delay)'),
        ),
        migrations.AddField(
            model_name='bot',
            name='typing_speed_min_ms',
            field=models.IntegerField(default=100, help_text='Minimum milliseconds per character for typing speed (base delay)'),
        ),
    ]
