# Generated by Django 5.2.3 on 2025-08-14 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0019_utterance_chat_history_used_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(help_text='The actual model ID used by the provider', max_length=255)),
                ('display_name', models.CharField(help_text='Human-readable name', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('capabilities', models.JSONField(default=list, help_text="List of capabilities like ['Chat', 'Reasoning', 'Code']")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['provider__name', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='ModelProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='bot',
            name='model_id',
            field=models.CharField(blank=True, default='gpt-4', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='model_type',
            field=models.CharField(blank=True, default='OpenAI', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='ai_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='chatbot.model'),
        ),
        migrations.AddField(
            model_name='model',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='chatbot.modelprovider'),
        ),
        migrations.AlterUniqueTogether(
            name='model',
            unique_together={('provider', 'model_id')},
        ),
    ]
