# Generated by Django 5.2.3 on 2025-08-14 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0020_model_modelprovider_alter_bot_model_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='ai_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='chatbot.model'),
        ),
    ]
