# Generated by Django 5.2.3 on 2025-08-14 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0020_model_modelprovider_alter_bot_model_id_and_more'),
    ]

    operations = [
        # This migration is reverted - we'll handle making ai_model non-nullable in 0023
        # after populating the data in 0022
    ]
