# Generated by Django 5.2.5 on 2025-08-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0025_populate_ai_model_for_existing_bots"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="avatar_prompt",
            field=models.TextField(
                blank=True,
                help_text="Prompt used for generating bot avatars. If empty, will use default prompt.",
                null=True,
            ),
        ),
    ]
