# Generated by Django 5.2.6 on 2025-09-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0028_alter_bot_max_transcript_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="reading_words_per_minute",
            field=models.IntegerField(
                default=250,
                help_text="Words per minute reading speed for calculating reading delay",
            ),
        ),
    ]
