# Generated by Django 5.2.6 on 2025-09-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0030_bot_moderation_harassment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModerationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="When disabled, all content moderation is bypassed globally",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Global Moderation Setting",
                "verbose_name_plural": "Global Moderation Settings",
            },
        ),
    ]
