# Generated by Django 5.2.7 on 2025-10-31 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0032_remove_bot_first_chunk_thinking_ms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="bot_config",
            field=models.TextField(blank=True, null=True),
        ),
    ]
