# -----------------------------------------------------------------------------
# s3.tf — the two S3 buckets this application uses
#
# I create two completely separate buckets with different purposes:
#
#   frontend_assets
#     Holds the compiled React application (HTML, JS, CSS).
#     Private — only CloudFront can read from it via Origin Access Control.
#     No public access whatsoever.
#
#   application_data
#     Holds everything the Django backend writes: bot avatar images,
#     user file uploads, and voice audio recordings from conversations.
#     Also private — the application reads and writes via its IAM role,
#     and generates short-lived presigned URLs when the frontend needs to
#     download a file directly.
#
# Both buckets block all public access. There is no static website hosting
# configured on either — CloudFront handles delivery for the frontend,
# and presigned URLs handle delivery for application data.
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# Frontend assets bucket
# -----------------------------------------------------------------------------

resource "aws_s3_bucket" "frontend_assets" {
  bucket = "${local.name_prefix}-frontend"

  tags = {
    Name    = "${local.name_prefix}-frontend"
    Purpose = "React application static files served via CloudFront"
  }
}

resource "aws_s3_bucket_versioning" "frontend_assets" {
  bucket = aws_s3_bucket.frontend_assets.id

  versioning_configuration {
    # Versioning lets me roll back a bad frontend deployment by pointing
    # CloudFront at a previous object version. Cheap insurance.
    status = "Enabled"
  }
}

resource "aws_s3_bucket_public_access_block" "frontend_assets" {
  bucket = aws_s3_bucket.frontend_assets.id

  # I block all public access. CloudFront uses Origin Access Control (OAC)
  # to authenticate with S3 using its own AWS identity — no public URLs needed.
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# -----------------------------------------------------------------------------
# Application data bucket
# -----------------------------------------------------------------------------

resource "aws_s3_bucket" "application_data" {
  bucket = "${local.name_prefix}-data"

  tags = {
    Name = "${local.name_prefix}-data"
  }

  # Prevent Terraform from passing tags in the CreateBucket call (us-east-1
  # rejects inline tagging for this bucket). Tags are applied via default_tags
  # at the provider level after creation.
  lifecycle {
    ignore_changes = [tags]
  }
}

resource "aws_s3_bucket_public_access_block" "application_data" {
  bucket = aws_s3_bucket.application_data.id

  # Private — the application accesses files via its EC2 instance role,
  # not via public URLs. The frontend gets temporary presigned URLs from
  # the Django API when it needs to show an avatar or play back audio.
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_cors_configuration" "application_data" {
  bucket = aws_s3_bucket.application_data.id

  cors_rule {
    # I allow the frontend to PUT files directly to S3 using presigned URLs
    # generated by the Django API. This avoids routing large file uploads
    # through the application server.
    allowed_headers = ["*"]
    allowed_methods = ["GET", "PUT", "POST", "DELETE", "HEAD"]
    allowed_origins = ["*"]
    expose_headers  = ["ETag"]
    max_age_seconds = 3000
  }
}
