# Generated by Django 5.1.7 on 2025-03-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keystroke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=255)),
                ('total_time_on_page', models.FloatField()),
                ('total_time_away_from_page', models.FloatField()),
                ('keystroke_count', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
