# Generated by Django 5.2.1 on 2025-05-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_bot_initial_utterance'),
    ]

    operations = [
        migrations.AddField(
            model_name='utterance',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='utterance_audio/'),
        ),
        migrations.AddField(
            model_name='utterance',
            name='is_voice',
            field=models.BooleanField(default=False),
        ),
    ]
