# Generated by Django 5.2.3 on 2025-07-11 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_control'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='image',
        ),
        migrations.AddField(
            model_name='avatar',
            name='image_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
