# Generated by Django 5.2.3 on 2025-07-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_remove_avatar_image_avatar_image_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='image_path',
            new_name='chatbot_avatar',
        ),
        migrations.AddField(
            model_name='avatar',
            name='condition',
            field=models.CharField(choices=[('control', 'control'), ('similar', 'similar'), ('dissimilar', 'dissimilar')], default='similar', max_length=20),
        ),
        migrations.AddField(
            model_name='avatar',
            name='participant_avatar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
