# Generated by Django 5.2.3 on 2025-08-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_add_chunk_messages_to_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('instructions', models.TextField(help_text='Instructions for this persona')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='bot',
            name='personas',
            field=models.ManyToManyField(blank=True, help_text='Select personas that this bot should embody', related_name='bots', to='chatbot.persona'),
        ),
    ]
