# Generated by Django 5.2.3 on 2025-08-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_conversation_selected_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='follow_up_instruction_prompt',
            field=models.TextField(blank=True, help_text='Instructions for generating follow-up messages when user is idle', null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='follow_up_on_idle',
            field=models.BooleanField(default=False, help_text='If true, bot will send follow-up messages when user is idle'),
        ),
        migrations.AddField(
            model_name='bot',
            name='idle_time_minutes',
            field=models.IntegerField(default=2, help_text='Minutes of inactivity before considering user idle'),
        ),
    ]
