# Generated by Django 5.2.5 on 2025-08-12 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0013_bot_humanlike_delay_control_humanlike_delay'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Control',
        ),
    ]
