# Generated by Django 5.2.3 on 2025-08-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0015_add_humanlike_delay_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='utterance',
            name='instruction_prompt',
            field=models.TextField(blank=True, help_text='The instruction prompt (bot prompt + persona) that was passed to the LLM for this utterance', null=True),
        ),
    ]
