# Generated by Django 5.2.3 on 2025-08-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0016_utterance_instruction_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='recurring_followup',
            field=models.BooleanField(default=False, help_text='If true, bot will keep sending follow-up messages while user is idle. If false, bot will only send one follow-up per idle period.'),
        ),
    ]
