# Generated by Django 5.2.3 on 2025-08-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0017_bot_recurring_followup'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='max_transcript_length',
            field=models.IntegerField(default=0, help_text='Maximum number of messages to include in chat history. 0 means no limit (include all messages).'),
        ),
    ]
