# Generated by Django 5.2.3 on 2025-08-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0018_bot_max_transcript_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='utterance',
            name='chat_history_used',
            field=models.TextField(blank=True, help_text='The chat history (formatted as JSON) that was actually passed to the LLM for this utterance', null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='max_transcript_length',
            field=models.IntegerField(default=0, help_text='Maximum number of messages to include in chat history. 0 = no chat history (only current message), 1+ = include that many most recent messages, negative = unlimited history.'),
        ),
    ]
