# Generated by Django 5.2.5 on 2025-08-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0023_make_ai_model_non_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot",
            name="model_id",
            field=models.CharField(
                blank=True, default="gpt-4o-mini", max_length=255, null=True
            ),
        ),
    ]
