# Generated by Django 5.2.5 on 2025-08-14 23:08

from django.db import migrations


def populate_avatar_prompt_default(apps, schema_editor):
    """Populate existing bots with default avatar prompt"""
    Bot = apps.get_model('chatbot', 'Bot')
    default_prompt = "Create a Bitmoji based on the given image. Accurately capture the person's facial features, but use a different hairstyle or hair color from the original image. Get rid of any accessories including earrings and glasses. Also, include only the face completely excluding the neck, shoulders, and body, and keep the facial expression neutral (neither smiling nor frowning). Make the output image square."
    
    # Update all bots that don't have an avatar_prompt set
    Bot.objects.filter(avatar_prompt__isnull=True).update(avatar_prompt=default_prompt)


def reverse_populate_avatar_prompt_default(apps, schema_editor):
    """Reverse the data migration - clear avatar_prompt for all bots"""
    Bot = apps.get_model('chatbot', 'Bot')
    Bot.objects.all().update(avatar_prompt=None)


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0026_add_avatar_prompt_to_bot"),
    ]

    operations = [
        migrations.RunPython(
            populate_avatar_prompt_default,
            reverse_populate_avatar_prompt_default,
        ),
    ]
