# Generated by Django 5.2.5 on 2025-08-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0027_populate_avatar_prompt_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot",
            name="max_transcript_length",
            field=models.IntegerField(
                default=-1,
                help_text="Maximum number of messages to include in chat history. 0 = no chat history (only current message), 1+ = include that many most recent messages, negative = unlimited history.",
            ),
        ),
    ]
