# Generated by Django 5.2.6 on 2025-09-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0029_bot_reading_words_per_minute"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="moderation_harassment",
            field=models.DecimalField(
                decimal_places=2,
                default=0.5,
                help_text="Harassment threshold (0.0-1.0, lower = stricter)",
                max_digits=3,
            ),
        ),
        migrations.AddField(
            model_name="bot",
            name="moderation_harassment_threatening",
            field=models.DecimalField(
                decimal_places=2,
                default=0.1,
                help_text="Harassment/threatening threshold (0.0-1.0, lower = stricter)",
                max_digits=3,
            ),
        ),
        migrations.AddField(
            model_name="bot",
            name="moderation_hate",
            field=models.DecimalField(
                decimal_places=2,
                default=0.5,
                help_text="Hate threshold (0.0-1.0, lower = stricter)",
                max_digits=3,
            ),
        ),
        migrations.AddField(
            model_name="bot",
            name="moderation_hate_threatening",
            field=models.DecimalField(
                decimal_places=2,
                default=0.1,
                help_text="Hate/threatening threshold (0.0-1.0, lower = stricter)",
                max_digits=3,
            ),
        ),
        migrations.AddField(
            model_name="bot",
            name="moderation_self_harm",
            field=models.DecimalField(
                decimal_places=2,
                default=0.2,
                help_text="Self-harm threshold (0.0-1.0, lower = stricter)",
                max_digits=3,
            ),
        ),
        migrations.AddField(
            model_name="bot",
            name="moderation_self_harm_instructions",
            field=models.DecimalField(
                decimal_places=2,
                default=0.5,
                help_text="Self-harm/instructions threshold (0.0-1.0, lower = stricter)",
                max_digits=3,
            ),
        ),
        migrations.AddField(
            model_name="bot",
            name="moderation_self_harm_intent",
            field=models.DecimalField(
                decimal_places=2,
                default=0.7,
                help_text="Self-harm/intent threshold (0.0-1.0, lower = stricter)",
                max_digits=3,
            ),
        ),
        migrations.AddField(
            model_name="bot",
            name="moderation_sexual",
            field=models.DecimalField(
                decimal_places=2,
                default=0.5,
                help_text="Sexual threshold (0.0-1.0, lower = stricter)",
                max_digits=3,
            ),
        ),
        migrations.AddField(
            model_name="bot",
            name="moderation_sexual_minors",
            field=models.DecimalField(
                decimal_places=2,
                default=0.2,
                help_text="Sexual/minors threshold (0.0-1.0, lower = stricter)",
                max_digits=3,
            ),
        ),
        migrations.AddField(
            model_name="bot",
            name="moderation_violence",
            field=models.DecimalField(
                decimal_places=2,
                default=0.7,
                help_text="Violence threshold (0.0-1.0, lower = stricter)",
                max_digits=3,
            ),
        ),
        migrations.AddField(
            model_name="bot",
            name="moderation_violence_graphic",
            field=models.DecimalField(
                decimal_places=2,
                default=0.8,
                help_text="Violence/graphic threshold (0.0-1.0, lower = stricter)",
                max_digits=3,
            ),
        ),
    ]
