# Generated by Django 5.2.6 on 2025-09-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0031_moderationsettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bot",
            name="first_chunk_thinking_ms",
        ),
        migrations.RemoveField(
            model_name="bot",
            name="last_chunk_pause_ms",
        ),
        migrations.RemoveField(
            model_name="bot",
            name="max_delay_ms",
        ),
        migrations.RemoveField(
            model_name="bot",
            name="min_delay_ms",
        ),
        migrations.RemoveField(
            model_name="bot",
            name="question_thinking_ms",
        ),
        migrations.RemoveField(
            model_name="bot",
            name="typing_speed_max_ms",
        ),
        migrations.RemoveField(
            model_name="bot",
            name="typing_speed_min_ms",
        ),
        migrations.AddField(
            model_name="bot",
            name="intra_message_delay_max",
            field=models.FloatField(
                default=0.3, help_text="Maximum delay between message parts in seconds"
            ),
        ),
        migrations.AddField(
            model_name="bot",
            name="intra_message_delay_min",
            field=models.FloatField(
                default=0.1, help_text="Minimum delay between message parts in seconds"
            ),
        ),
        migrations.AddField(
            model_name="bot",
            name="min_reading_delay",
            field=models.FloatField(
                default=1.0, help_text="Minimum reading delay in seconds"
            ),
        ),
        migrations.AddField(
            model_name="bot",
            name="reading_jitter_max",
            field=models.FloatField(
                default=0.3, help_text="Maximum reading jitter in seconds"
            ),
        ),
        migrations.AddField(
            model_name="bot",
            name="reading_jitter_min",
            field=models.FloatField(
                default=0.1, help_text="Minimum reading jitter in seconds"
            ),
        ),
        migrations.AddField(
            model_name="bot",
            name="reading_thinking_max",
            field=models.FloatField(
                default=0.5, help_text="Maximum reading thinking time in seconds"
            ),
        ),
        migrations.AddField(
            model_name="bot",
            name="reading_thinking_min",
            field=models.FloatField(
                default=0.2, help_text="Minimum reading thinking time in seconds"
            ),
        ),
        migrations.AddField(
            model_name="bot",
            name="writing_jitter_max",
            field=models.FloatField(
                default=0.15, help_text="Maximum writing jitter in seconds"
            ),
        ),
        migrations.AddField(
            model_name="bot",
            name="writing_jitter_min",
            field=models.FloatField(
                default=0.05, help_text="Minimum writing jitter in seconds"
            ),
        ),
        migrations.AddField(
            model_name="bot",
            name="writing_thinking_max",
            field=models.FloatField(
                default=0.3, help_text="Maximum writing thinking time in seconds"
            ),
        ),
        migrations.AddField(
            model_name="bot",
            name="writing_thinking_min",
            field=models.FloatField(
                default=0.1, help_text="Minimum writing thinking time in seconds"
            ),
        ),
        migrations.AddField(
            model_name="bot",
            name="writing_words_per_minute",
            field=models.FloatField(
                default=200.0,
                help_text="Words per minute writing speed for calculating writing delay",
            ),
        ),
        migrations.AlterField(
            model_name="bot",
            name="reading_words_per_minute",
            field=models.FloatField(
                default=250.0,
                help_text="Words per minute reading speed for calculating reading delay",
            ),
        ),
    ]
