# Generated by Django 5.2.17 on 2026-08-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0033_conversation_bot_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="utterance",
            name="moderation_category",
            field=models.CharField(
                blank=True,
                help_text="Moderation category that blocked this exchange (e.g. 'harassment'); null if the message was not blocked",
                max_length=64,
                null=True,
            ),
        ),
    ]
