# Generated by Django 5.2.17 on 2026-08-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0034_utterance_moderation_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="utterance",
            name="moderation_scores",
            field=models.JSONField(
                blank=True,
                help_text="Full moderation category→score map for the blocked message; null if the message was not blocked",
                null=True,
            ),
        ),
    ]
