# Generated by Django 5.2.17 on 2026-08-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0036_backfill_moderation_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="moderation_illicit",
            field=models.DecimalField(
                decimal_places=2,
                default=0.5,
                help_text="Illicit behaviour threshold (0.0-1.0, lower = stricter)",
                max_digits=3,
            ),
        ),
        migrations.AddField(
            model_name="bot",
            name="moderation_illicit_violent",
            field=models.DecimalField(
                decimal_places=2,
                default=0.1,
                help_text="Illicit/violent threshold (0.0-1.0, lower = stricter)",
                max_digits=3,
            ),
        ),
    ]
